/*
 * Keyfactor-v1
 * This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.keyfactor.command.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.keyfactor.command.client.model.ModelsSSHAccessLogonUserAccessResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.keyfactor.command.client.JSON;

/**
 * ModelsSSHAccessServerGroupAccessResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ModelsSSHAccessServerGroupAccessResponse {
  public static final String SERIALIZED_NAME_SERVER_GROUP_ID = "ServerGroupId";
  @SerializedName(SERIALIZED_NAME_SERVER_GROUP_ID)
  private UUID serverGroupId;

  public static final String SERIALIZED_NAME_LOGON_USERS = "LogonUsers";
  @SerializedName(SERIALIZED_NAME_LOGON_USERS)
  private List<ModelsSSHAccessLogonUserAccessResponse> logonUsers = null;

  public ModelsSSHAccessServerGroupAccessResponse() {
  }

  public ModelsSSHAccessServerGroupAccessResponse serverGroupId(UUID serverGroupId) {
    
    this.serverGroupId = serverGroupId;
    return this;
  }

   /**
   * Get serverGroupId
   * @return serverGroupId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "00000000-0000-0000-0000-000000000000", value = "")

  public UUID getServerGroupId() {
    return serverGroupId;
  }


  public void setServerGroupId(UUID serverGroupId) {
    this.serverGroupId = serverGroupId;
  }


  public ModelsSSHAccessServerGroupAccessResponse logonUsers(List<ModelsSSHAccessLogonUserAccessResponse> logonUsers) {
    
    this.logonUsers = logonUsers;
    return this;
  }

  public ModelsSSHAccessServerGroupAccessResponse addLogonUsersItem(ModelsSSHAccessLogonUserAccessResponse logonUsersItem) {
    if (this.logonUsers == null) {
      this.logonUsers = new ArrayList<>();
    }
    this.logonUsers.add(logonUsersItem);
    return this;
  }

   /**
   * Get logonUsers
   * @return logonUsers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ModelsSSHAccessLogonUserAccessResponse> getLogonUsers() {
    return logonUsers;
  }


  public void setLogonUsers(List<ModelsSSHAccessLogonUserAccessResponse> logonUsers) {
    this.logonUsers = logonUsers;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsSSHAccessServerGroupAccessResponse modelsSSHAccessServerGroupAccessResponse = (ModelsSSHAccessServerGroupAccessResponse) o;
    return Objects.equals(this.serverGroupId, modelsSSHAccessServerGroupAccessResponse.serverGroupId) &&
        Objects.equals(this.logonUsers, modelsSSHAccessServerGroupAccessResponse.logonUsers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serverGroupId, logonUsers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsSSHAccessServerGroupAccessResponse {\n");
    sb.append("    serverGroupId: ").append(toIndentedString(serverGroupId)).append("\n");
    sb.append("    logonUsers: ").append(toIndentedString(logonUsers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ServerGroupId");
    openapiFields.add("LogonUsers");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ModelsSSHAccessServerGroupAccessResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ModelsSSHAccessServerGroupAccessResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ModelsSSHAccessServerGroupAccessResponse is not found in the empty JSON string", ModelsSSHAccessServerGroupAccessResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ModelsSSHAccessServerGroupAccessResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ModelsSSHAccessServerGroupAccessResponse` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("ServerGroupId") != null && !jsonObj.get("ServerGroupId").isJsonNull()) && !jsonObj.get("ServerGroupId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ServerGroupId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ServerGroupId").toString()));
      }
      if (jsonObj.get("LogonUsers") != null && !jsonObj.get("LogonUsers").isJsonNull()) {
        JsonArray jsonArraylogonUsers = jsonObj.getAsJsonArray("LogonUsers");
        if (jsonArraylogonUsers != null) {
          // ensure the json data is an array
          if (!jsonObj.get("LogonUsers").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `LogonUsers` to be an array in the JSON string but got `%s`", jsonObj.get("LogonUsers").toString()));
          }

          // validate the optional field `LogonUsers` (array)
          for (int i = 0; i < jsonArraylogonUsers.size(); i++) {
            ModelsSSHAccessLogonUserAccessResponse.validateJsonObject(jsonArraylogonUsers.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ModelsSSHAccessServerGroupAccessResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ModelsSSHAccessServerGroupAccessResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ModelsSSHAccessServerGroupAccessResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ModelsSSHAccessServerGroupAccessResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ModelsSSHAccessServerGroupAccessResponse>() {
           @Override
           public void write(JsonWriter out, ModelsSSHAccessServerGroupAccessResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ModelsSSHAccessServerGroupAccessResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ModelsSSHAccessServerGroupAccessResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ModelsSSHAccessServerGroupAccessResponse
  * @throws IOException if the JSON string is invalid with respect to ModelsSSHAccessServerGroupAccessResponse
  */
  public static ModelsSSHAccessServerGroupAccessResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ModelsSSHAccessServerGroupAccessResponse.class);
  }

 /**
  * Convert an instance of ModelsSSHAccessServerGroupAccessResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

