/*
 * Keyfactor-v1
 * This reference serves to document REST-based methods to manage and integrate with Keyfactor. In addition, an embedded interface allows for the execution of calls against the current Keyfactor API instance.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.keyfactor.command.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.keyfactor.command.client.JSON;

/**
 * ModelsSSHLogonsLogonQueryResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class ModelsSSHLogonsLogonQueryResponse {
  public static final String SERIALIZED_NAME_ID = "Id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_USERNAME = "Username";
  @SerializedName(SERIALIZED_NAME_USERNAME)
  private String username;

  public static final String SERIALIZED_NAME_LAST_LOGON = "LastLogon";
  @SerializedName(SERIALIZED_NAME_LAST_LOGON)
  private OffsetDateTime lastLogon;

  public static final String SERIALIZED_NAME_SERVER_ID = "ServerId";
  @SerializedName(SERIALIZED_NAME_SERVER_ID)
  private Integer serverId;

  public static final String SERIALIZED_NAME_SERVER_NAME = "ServerName";
  @SerializedName(SERIALIZED_NAME_SERVER_NAME)
  private String serverName;

  public static final String SERIALIZED_NAME_GROUP_NAME = "GroupName";
  @SerializedName(SERIALIZED_NAME_GROUP_NAME)
  private String groupName;

  public static final String SERIALIZED_NAME_KEY_COUNT = "KeyCount";
  @SerializedName(SERIALIZED_NAME_KEY_COUNT)
  private Integer keyCount;

  public static final String SERIALIZED_NAME_SERVER_UNDER_MANAGEMENT = "ServerUnderManagement";
  @SerializedName(SERIALIZED_NAME_SERVER_UNDER_MANAGEMENT)
  private Boolean serverUnderManagement;

  public ModelsSSHLogonsLogonQueryResponse() {
  }

  public ModelsSSHLogonsLogonQueryResponse id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public ModelsSSHLogonsLogonQueryResponse username(String username) {
    
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUsername() {
    return username;
  }


  public void setUsername(String username) {
    this.username = username;
  }


  public ModelsSSHLogonsLogonQueryResponse lastLogon(OffsetDateTime lastLogon) {
    
    this.lastLogon = lastLogon;
    return this;
  }

   /**
   * Get lastLogon
   * @return lastLogon
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getLastLogon() {
    return lastLogon;
  }


  public void setLastLogon(OffsetDateTime lastLogon) {
    this.lastLogon = lastLogon;
  }


  public ModelsSSHLogonsLogonQueryResponse serverId(Integer serverId) {
    
    this.serverId = serverId;
    return this;
  }

   /**
   * Get serverId
   * @return serverId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getServerId() {
    return serverId;
  }


  public void setServerId(Integer serverId) {
    this.serverId = serverId;
  }


  public ModelsSSHLogonsLogonQueryResponse serverName(String serverName) {
    
    this.serverName = serverName;
    return this;
  }

   /**
   * Get serverName
   * @return serverName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getServerName() {
    return serverName;
  }


  public void setServerName(String serverName) {
    this.serverName = serverName;
  }


  public ModelsSSHLogonsLogonQueryResponse groupName(String groupName) {
    
    this.groupName = groupName;
    return this;
  }

   /**
   * Get groupName
   * @return groupName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getGroupName() {
    return groupName;
  }


  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }


  public ModelsSSHLogonsLogonQueryResponse keyCount(Integer keyCount) {
    
    this.keyCount = keyCount;
    return this;
  }

   /**
   * Get keyCount
   * @return keyCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getKeyCount() {
    return keyCount;
  }


  public void setKeyCount(Integer keyCount) {
    this.keyCount = keyCount;
  }


  public ModelsSSHLogonsLogonQueryResponse serverUnderManagement(Boolean serverUnderManagement) {
    
    this.serverUnderManagement = serverUnderManagement;
    return this;
  }

   /**
   * Get serverUnderManagement
   * @return serverUnderManagement
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getServerUnderManagement() {
    return serverUnderManagement;
  }


  public void setServerUnderManagement(Boolean serverUnderManagement) {
    this.serverUnderManagement = serverUnderManagement;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelsSSHLogonsLogonQueryResponse modelsSSHLogonsLogonQueryResponse = (ModelsSSHLogonsLogonQueryResponse) o;
    return Objects.equals(this.id, modelsSSHLogonsLogonQueryResponse.id) &&
        Objects.equals(this.username, modelsSSHLogonsLogonQueryResponse.username) &&
        Objects.equals(this.lastLogon, modelsSSHLogonsLogonQueryResponse.lastLogon) &&
        Objects.equals(this.serverId, modelsSSHLogonsLogonQueryResponse.serverId) &&
        Objects.equals(this.serverName, modelsSSHLogonsLogonQueryResponse.serverName) &&
        Objects.equals(this.groupName, modelsSSHLogonsLogonQueryResponse.groupName) &&
        Objects.equals(this.keyCount, modelsSSHLogonsLogonQueryResponse.keyCount) &&
        Objects.equals(this.serverUnderManagement, modelsSSHLogonsLogonQueryResponse.serverUnderManagement);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, username, lastLogon, serverId, serverName, groupName, keyCount, serverUnderManagement);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelsSSHLogonsLogonQueryResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    lastLogon: ").append(toIndentedString(lastLogon)).append("\n");
    sb.append("    serverId: ").append(toIndentedString(serverId)).append("\n");
    sb.append("    serverName: ").append(toIndentedString(serverName)).append("\n");
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    keyCount: ").append(toIndentedString(keyCount)).append("\n");
    sb.append("    serverUnderManagement: ").append(toIndentedString(serverUnderManagement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Id");
    openapiFields.add("Username");
    openapiFields.add("LastLogon");
    openapiFields.add("ServerId");
    openapiFields.add("ServerName");
    openapiFields.add("GroupName");
    openapiFields.add("KeyCount");
    openapiFields.add("ServerUnderManagement");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ModelsSSHLogonsLogonQueryResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ModelsSSHLogonsLogonQueryResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ModelsSSHLogonsLogonQueryResponse is not found in the empty JSON string", ModelsSSHLogonsLogonQueryResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ModelsSSHLogonsLogonQueryResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ModelsSSHLogonsLogonQueryResponse` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("Username") != null && !jsonObj.get("Username").isJsonNull()) && !jsonObj.get("Username").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Username` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Username").toString()));
      }
      if ((jsonObj.get("ServerName") != null && !jsonObj.get("ServerName").isJsonNull()) && !jsonObj.get("ServerName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ServerName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ServerName").toString()));
      }
      if ((jsonObj.get("GroupName") != null && !jsonObj.get("GroupName").isJsonNull()) && !jsonObj.get("GroupName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `GroupName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("GroupName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ModelsSSHLogonsLogonQueryResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ModelsSSHLogonsLogonQueryResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ModelsSSHLogonsLogonQueryResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ModelsSSHLogonsLogonQueryResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<ModelsSSHLogonsLogonQueryResponse>() {
           @Override
           public void write(JsonWriter out, ModelsSSHLogonsLogonQueryResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ModelsSSHLogonsLogonQueryResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ModelsSSHLogonsLogonQueryResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ModelsSSHLogonsLogonQueryResponse
  * @throws IOException if the JSON string is invalid with respect to ModelsSSHLogonsLogonQueryResponse
  */
  public static ModelsSSHLogonsLogonQueryResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ModelsSSHLogonsLogonQueryResponse.class);
  }

 /**
  * Convert an instance of ModelsSSHLogonsLogonQueryResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

